version: "3"
services:
  db:
    image: "postgres"
    container_name: "disc_postgres"
    environment:
     - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5532:5432"
    volumes:
      - disc_sql:/var/lib/postgresql/data
volumes:
  disc_sql:
